### ISSUE TITLE
Upgrade to Angular 4?

### ISSUE THREAD

**Issue by lamquangphuc** [NerdyHippie/angularfire2-project-seed#1]
Can you upgrade your project to support to Angular 4?

**Comment by joshorvis** [comment]
I plan to but have not had time yet.  Happy to accept a pull request if you beat me to it.

**Comment by lundcm** [comment]
@joshorvis - Any update on this? I'm trying to do it myself right now but I'm having quite a time with the auth piece of it. I upgraded the version of angularfire as well, but it looks like angularfire has changed a lot. Just curious if you've done any of this work before I get too far into it.

-- Thanks

**Comment by joshorvis** [comment]
Just updated to Angular5 with current versions of all other libraries
